[platformio]
default_envs = seeed_xiao_esp32c3

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/ftservo/FTServo_Arduino.git#64922cda46e56b21b8c1d9e830d936a1941645ae
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
