#pragma once

#include <Arduino.h>

// Generated by arm/ik/solve_fixed_poses.py. Do not edit by hand.
static constexpr bool POSE_TABLE_CONFIGURED = true;

struct ArmPose { int16_t body[5]; };

static constexpr uint8_t SERVO_IDS[6] = {1, 2, 3, 4, 5, 6};
static constexpr int16_t JOINT_MIN_TICKS[6] = {640, 925, 979, 1716, 242, 1805};
static constexpr int16_t JOINT_MAX_TICKS[6] = {3188, 3166, 2993, 3804, 3884, 2308};
static constexpr int16_t GRIPPER_OPEN_TICK = 2288;
static constexpr int16_t GRIPPER_CLOSED_TICK = 1825;

static constexpr ArmPose POSE_HOME = {{1896, 952, 2667, 3665, 3019}};
static constexpr ArmPose POSE_APPROACH_FORK = {{1730, 2049, 2284, 3505, 2863}};
static constexpr ArmPose POSE_PICK_FORK = {{1730, 2186, 2282, 3380, 2855}};
static constexpr ArmPose POSE_APPROACH_CHOPSTICKS = {{1812, 2086, 2282, 3474, 2988}};
static constexpr ArmPose POSE_PICK_CHOPSTICKS = {{1841, 2198, 2254, 3464, 3022}};
static constexpr ArmPose POSE_APPROACH_PLACE = {{2846, 1838, 2363, 3473, 3022}};
static constexpr ArmPose POSE_PLACE_UTENSIL = {{2847, 2089, 2346, 3464, 3011}};
static constexpr ArmPose POSE_RETREAT = {{2421, 961, 2682, 3672, 3019}};
